# Based on: https://github.com/marketplace/actions/setup-miniconda#example-1-basic-usage

name: Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: macOS-latest}
          - {os: ubuntu-18.04}
          - {os: ubuntu-latest}
    name: Checking with mypy and black ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip
      - run: pip install "black<23" "mypy" "snakefmt"
      - run: black --diff .
      - run: snakefmt .
      - run: mypy --strict .
