# Based on: https://github.com/marketplace/actions/setup-miniconda#example-1-basic-usage

name: Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: macOS-latest}
          - {os: ubuntu-18.04}
          - {os: ubuntu-latest}
    name: Checking with mypy and black ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Conda setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: juno_library/envs/juno_library.yaml 
          activate-environment: juno_library
      - run: pip install "black<23" "mypy" "snakefmt"
      - run: black --diff --check .
      - run: snakefmt --check .
      - run: mypy --strict .
