name: Unit tests

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest}
          - {os: ubuntu-18.04}
          - {os: ubuntu-latest}
    name: Testing main classes ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: envs/juno_library.yaml
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install juno-library with pip
        shell: bash -l {0}
        run: pip install -e .
      - name: Unit tests
        shell: bash -l {0}
        run: python tests/library_tests.py
